"""Initial migration.

Revision ID: 8ef1f17ad11a
Revises: f1b828fc0ee3
Create Date: 2024-04-03 12:56:28.936021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ef1f17ad11a'
down_revision = 'f1b828fc0ee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('user')
    op.drop_table('cart')
    op.add_column('products', sa.Column('image_url', sa.String(), nullable=False))
    op.add_column('products', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_products_admin_id_admin'), 'products', 'admin', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_products_admin_id_admin'), 'products', type_='foreignkey')
    op.drop_column('products', 'admin_id')
    op.drop_column('products', 'quantity')
    op.drop_column('products', 'image_url')
    op.create_table('cart',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_cart_product_id_products'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_cart_user_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('contact', sa.VARCHAR(), nullable=True),
    sa.Column('password', sa.VARCHAR(length=60), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('admin')
    # ### end Alembic commands ###
